# Generated by Django 4.1 on 2023-12-01 16:53

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('url_image', models.ImageField(null=True, upload_to=api.models.user_image_field)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_agency', models.CharField(default=9090, max_length=4)),
                ('account_number', models.CharField(max_length=8, unique=True)),
                ('account_type', models.CharField(default='Standart', max_length=20)),
                ('account_balance', models.FloatField(default=0.0, max_length=20)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('obs', models.TextField(blank=True, max_length=100)),
                ('type_transfer', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_destinantion', to='api.account')),
                ('origin_id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_origin', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movimentation_value', models.FloatField()),
                ('movimentation_obs', models.TextField(max_length=100)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_id_movimentation', to='api.account')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_value', models.FloatField()),
                ('loan_interest', models.FloatField()),
                ('loan_quantity_parcelas', models.IntegerField()),
                ('loan_obs', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_loan', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('contact_email', models.EmailField(max_length=50, unique=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('card_cvv', models.CharField(max_length=3)),
                ('card_valid', models.DateField()),
                ('card_flag', models.CharField(max_length=20)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_logradouro', models.CharField(max_length=10)),
                ('address_neighborhood', models.CharField(max_length=30)),
                ('city_address', models.CharField(max_length=30)),
                ('address_street', models.CharField(max_length=20)),
                ('address_uf', models.CharField(max_length=2)),
                ('address_cep', models.CharField(max_length=8)),
                ('client_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
