# Generated by Django 4.1 on 2023-12-01 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_id_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_destino', to='api.conta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta_id_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_origem', to='api.conta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_transacao', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta')),
            ],
        ),
    ]
